# Generated by Django 4.2.8 on 2023-12-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Account',
        ),
    ]
